mongodb:
  uri: "mongodb://mongodb-service:27017"

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels:
    release: prometheus
    